### ISSUE TITLE
Allow passing of context array in `apply` and `can` methods.

### ISSUE THREAD

**Issue by leonelngande** [iben12/laravel-statable#18]
Hi 👋,

Decided to create an issue before moving on with a pull request for this. 
"sebdesign/laravel-state-machine": "^2.1" introduces the ability to pass a context array to stateMachine@apply and stateMachine@can, [documented here](https://github.com/sebdesign/laravel-state-machine/issues/31).

I've checked and this package is still using "sebdesign/laravel-state-machine": "^2.0", and support for the above feature is missing.

Is it ok if I go ahead and update to version 2.1 and update the Statable trait methods `apply` and `canApply` to accept a context array? e.g `apply('to_reviewed', false, ['foo' => 'bar'])`.

**Comment by iben12** [comment]
PR merged, thanks!

**Comment by petermein** [comment]
This PR is breaking the interface in newer PHP versions .


Declaration of Sebdesign\SM\StateMachine\StateMachine::apply($transition, bool $soft = false, array $context = Array): bool must be compatible with SM\StateMachine\StateMachine::apply(string $transition, $soft = false): bool

**Comment by iben12** [comment]
I tried to figure out what breaks (on PHP 7.4.7), but could not find it.

The only place we call `apply` is [here](https://github.com/iben12/laravel-statable/blob/b22761a69250c48881da879194d85711bdf349cf/src/Statable.php#L69):
```
return $this->stateMachine()->apply($transition, $soft, $context);
```
and it seems to be compatible with [Sebdesign's implementation](https://github.com/sebdesign/laravel-state-machine/blob/ebd02937550acd0874a873ddfd56bb1724c3a4e0/src/StateMachine/StateMachine.php#L75):
```
public function apply($transition, bool $soft = false, array $context = []): bool
```

If you mean [this](https://github.com/winzou/state-machine/blob/da3ef733d00795b144bc12a42a66cf9649829b41/src/SM/StateMachine/StateMachineInterface.php#L39) in the upstream winzou/state-machine:
```
public function apply(string $transition, $soft = false): bool;
```
then `Statable` must not be compatible with it, because Sebdesign's implementation wraps it for us and applies the state via property accessor in the [`setState`](https://github.com/sebdesign/laravel-state-machine/blob/98e05b640018738249b4b6d63f1773615eb57a06/src/StateMachine/StateMachine.php#L119) method.
